### ISSUE TITLE
[Bug?] Using environment variables for icon renders it unidentifiable.

### ISSUE THREAD

**Issue by Fooughhy** [lextm/windowsterminal-shell#5]
Hi! Really nice script for adding the profiles to the context menu! 

I use a custom icon for my Git-Bash profile (actually don't know if it is custom, or default), but it uses an env variable (%PROGRAMFILES%).
Running the script adds the item to the context menu, but outputs the error:
>WARNING: Didn't find icon for profile Git-Bash
I have the following as the icon path `"icon" : "%PROGRAMFILES%\\Git\\mingw64\\share\\git\\git-for-windows.ico"`.

I am also getting this for my WSL profile, which doesn't use a custom icon (i.e there is no "icon" item in it's profile config).
Do you know of any reason this might be the case?

**Comment by lextm** [comment]
Thanks for reporting this. Will investigate later.

**Comment by lextm** [comment]
Fixed it. You just need to run `install.ps1` again.

**Comment by Fooughhy** [comment]
Thanks! Fast work!
One problem still though, but I don't know if I should create a new issue.

PSA: Found this out while writing this comment.
The powershell settings allow for both unix paths and escaped windows paths (i.e `C:\\Git\\etc\\etc` and `C:/Git/etc/etc`) for their icon paths. This script only seems to work with the former way.

**Comment by lextm** [comment]
Can you open another issue?
